import * as vscode from 'vscode';
import { execFile } from 'child_process';
import { promisify } from 'util';
import { mkdir, writeFile } from 'fs/promises';
import * as path from 'path';
import { Draft, ApplyResult, WorkflowState, NotebookDraftPayload, PowerBIDraftPayload, ExternalConnectionDraftPayload, MetadataDraftPayload } from './domain';

const execFileAsync = promisify(execFile);

export interface DeploymentFile { relativePath: string; content: string; }
export interface DeploymentBlueprint { target: string; files: DeploymentFile[]; commands: string[]; deployCommand?: { command: string; args: string[] }; }
export interface DeploymentServiceOptions { workspaceRoot?: string; outputFolder?: string; autoApply?: boolean; }

export class DeploymentService {
  public constructor(private readonly options: DeploymentServiceOptions = {}) {}

  public static isDeployable(draft: Draft): boolean {
    return ['deployment-review', 'semantic-model-review', 'external-connection-review', 'metadata-grid'].includes(draft.draftType);
  }

  public async apply(draft: Draft, _state: WorkflowState): Promise<ApplyResult> {
    const completedAt = new Date().toISOString();
    const workspaceRoot = this.options.workspaceRoot ?? vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
    const outputFolderSetting = this.options.outputFolder ?? vscode.workspace.getConfiguration('lakepilot.deployment').get<string>('outputFolder', '.lakepilot/deploy');
    const autoApply = this.options.autoApply ?? vscode.workspace.getConfiguration('lakepilot.deployment').get<boolean>('autoApply', false);
    if (!workspaceRoot) {
      return { status: 'failed', target: draft.draftType, outputFolder: outputFolderSetting, writtenFiles: [], commands: [], logs: ['No workspace folder is open. Open a workspace before applying LakePilot drafts.'], completedAt };
    }
    const outputFolder = path.join(workspaceRoot, outputFolderSetting);
    const logs: string[] = [];
    const writtenFiles: string[] = [];
    const blueprint = buildDeploymentBlueprint(draft);
    try {
      for (const file of blueprint.files) {
        const absolutePath = path.join(outputFolder, file.relativePath);
        await mkdir(path.dirname(absolutePath), { recursive: true });
        await writeFile(absolutePath, file.content, 'utf8');
        writtenFiles.push(absolutePath);
      }
      let status: ApplyResult['status'] = 'simulated';
      if (autoApply && blueprint.deployCommand && await this.hasDatabricksCli()) {
        const { stdout, stderr } = await execFileAsync(blueprint.deployCommand.command, blueprint.deployCommand.args, { cwd: outputFolder });
        logs.push(stdout.trim(), stderr.trim());
        status = 'applied';
      } else if (autoApply && blueprint.deployCommand) {
        logs.push('Databricks CLI was not detected; deployment remains simulated.');
      } else {
        logs.push('Auto-apply is disabled; files were written for review only.');
      }
      return { status, target: blueprint.target, outputFolder, writtenFiles, commands: blueprint.commands, logs: logs.filter(Boolean), completedAt };
    } catch (error) {
      return { status: 'failed', target: blueprint.target, outputFolder, writtenFiles, commands: blueprint.commands, logs: [error instanceof Error ? error.message : 'Unknown deployment failure'], completedAt };
    }
  }

  private async hasDatabricksCli(): Promise<boolean> {
    try {
      await execFileAsync('databricks', ['--version']);
      return true;
    } catch {
      return false;
    }
  }
}

export function buildDeploymentBlueprint(draft: Draft): DeploymentBlueprint {
  switch (draft.draftType) {
    case 'deployment-review': return databricksBlueprint(draft.payload as NotebookDraftPayload);
    case 'semantic-model-review': return powerBiBlueprint(draft.payload as PowerBIDraftPayload);
    case 'external-connection-review': return connectionBlueprint(draft.payload as ExternalConnectionDraftPayload);
    case 'metadata-grid': return metadataBlueprint(draft.payload as MetadataDraftPayload);
    default: return { target: draft.draftType, files: [], commands: [] };
  }
}

function databricksBlueprint(payload: NotebookDraftPayload): DeploymentBlueprint {
  const scenario = safe(payload.scenario);
  const root = `databricks/${scenario}`;
  const files: DeploymentFile[] = [
    { relativePath: `${root}/src/clean_report_source.py`, content: payload.notebookSource },
    { relativePath: `${root}/databricks.yml`, content: `bundle:\n  name: ${scenario}\nresources:\n  jobs: {}\n` },
    { relativePath: `${root}/README.md`, content: `# ${scenario}\n\nReview-only Databricks Asset Bundle generated by LakePilot.\n` }
  ];
  if (payload.jobJson) files.push({ relativePath: `${root}/resources/job.json`, content: payload.jobJson });
  return { target: 'databricks-assets', files, commands: ['databricks bundle deploy'], deployCommand: { command: 'databricks', args: ['bundle', 'deploy'] } };
}

function powerBiBlueprint(payload: PowerBIDraftPayload): DeploymentBlueprint {
  const scenario = safe(payload.dataConnection.table || 'lakepilot-report');
  return {
    target: 'powerbi-assets',
    files: [
      { relativePath: `powerbi/${scenario}/${scenario}.SemanticModel/definition/model.tmdl`, content: payload.semanticModel.tmdl },
      { relativePath: `powerbi/${scenario}/${scenario}.SemanticModel/definition/expressions.tmdl`, content: `expression DatabricksSource =\n\t${payload.dataConnection.powerQueryM.replace(/\n/g, '\n\t')}\n` },
      { relativePath: `powerbi/${scenario}/${scenario}.pbip`, content: JSON.stringify({ version: '1.0', artifacts: [{ report: { path: `${scenario}.Report` } }, { semanticModel: { path: `${scenario}.SemanticModel` } }] }, null, 2) },
      { relativePath: `powerbi/${scenario}/${scenario}.Report/report.json`, content: JSON.stringify({ pages: payload.reportPages, visuals: payload.visualPlan }, null, 2) },
      { relativePath: `powerbi/${scenario}/${scenario}.connection.md`, content: [`# Databricks SQL endpoint`, `Mode: ${payload.dataConnection.connectivityMode}`, `Host: ${payload.dataConnection.serverHostname}`, `HTTP Path: ${payload.dataConnection.httpPath}`, `Table: ${payload.dataConnection.catalog}.${payload.dataConnection.schema}.${payload.dataConnection.table}`, `SQL: ${payload.dataConnection.sqlEndpointQuery}`].join('\n') }
    ],
    commands: ['Review PBIP files in Power BI Desktop', 'databricks bundle deploy']
  };
}

function connectionBlueprint(payload: ExternalConnectionDraftPayload): DeploymentBlueprint {
  const scenario = safe(payload.connectionName);
  return { target: 'external-connection', files: [{ relativePath: `connections/${scenario}/README.md`, content: payload.ingestionNotes.join('\n') }, { relativePath: `connections/${scenario}/connection.json`, content: payload.configJson }], commands: ['Review external connection before use'] };
}

function metadataBlueprint(payload: MetadataDraftPayload): DeploymentBlueprint {
  const scenario = safe(`${payload.catalog}-${payload.schema}-${payload.table}`);
  return { target: 'metadata', files: [{ relativePath: `metadata/${scenario}/metadata.json`, content: JSON.stringify(payload, null, 2) }, { relativePath: `metadata/${scenario}/README.md`, content: `# Metadata for ${payload.catalog}.${payload.schema}.${payload.table}\n` }], commands: ['Review metadata grid before publishing'] };
}

function safe(value: string): string { return value.toLowerCase().replace(/[^a-z0-9-_]+/g, '-').replace(/^-|-$/g, '') || 'lakepilot'; }
